### PR TITLE
Adding GitHub's Super-Linter

### PR DESCRIPTION
**Pull request by bikramnehra**
for details see: 
https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/
https://github.com/marketplace/actions/super-linter

### CODE REVIEW

**Comment by bikramnehra** [comment]
@viccuad let me know if this makes sense. I can update the PR to get rid of travis.

**Comment by viccuad** [comment]
This looks cool! 

Looking at the linting run on this PR, I see
```
--------------------------------------------
Gathering user validation information...
- Only validating [new], or [edited] files in code base...
awk: cmd. line:1: Unexpected end of string
awk: cmd. line:1: Unexpected end of string

```

Which I wonder if it is ok. I personally would lint the full repo every time, and not only the changes (which also protects us from direct commits to master). What do you folks think?

On a related note, I would like to have all the shell code in cap-ci in .sh files, out of yamls, so it can get linted properly (but I suppose that should happen in a different PR).

**Review by HartS — APPROVED** [review]
I noticed the latest super-linter version is v2.2.2 . Otherwise LGTM.

It might be useful to add a pre-commit hook that generates all indexed pipelines and commits them in a `lint/` path to be evaluated by the yaml linters. Would need to check that files didn't have unstaged changes however.

**Comment by viccuad** [comment]
Does the linter lint shellscripts? (the output from the job doesn't tell what was linted)

**Pull request merged**
